inbounddepartureairports = {"PMI": "Palma de Mallorca"}
inboundarrivalairports = {"HAJ": "Hannover",
                          "FRA": "Frankfurt",
                          "ZRH": "Zürich",
                          "LEJ": "Leipzig/Halle",
                          "NUE": "Nürnberg",
                          "SXB": "Straßburg",
                          "BSL": "Basel Mulhouse Freiburg",
                          "DUS": "Düsseldorf",
                          "EIN": "Eindhoven",
                          "BRU": "Brussels",
                          "LUX": "Luxemburg",
                          "FKB": "Karlsruhe / Baden-Baden",
                          "VIE": "Wien",
                          "HAM": "Hamburg",
                          "NRN": "Weeze",
                          "SCN": "Saarbrücken",
                          "KRK": "Rijeka",
                          "STR": "Stuttgart",
                          "CGN": "Köln Bonn",
                          "DTM": "Dortmund",
                          "FMO": "Münster/Osnabrück",
                          "GRQ": "Groningen",
                          "BRE": "Bremen",
                          "GWT": "Sylt",
                          "WAW": "Warschau",
                          "BRS": "Bristol",
                          "PRG": "Prag",
                          "MUC": "München",
                          "BER": "Berlin",
                          "BRN": "Bern",
                          "GRZ": "Graz",
                          "KLU": "Klagenfurt am Wörthersee",
                          "GVA": "Genf",
                          "SZG": "Salzburg",
                          "FDH": "Bodensee-Airport Friedrichshafen",
                          "BLL": "Billund",
                          "KSF": "Kassel",
                          "PAD": "Paderborn-Lippstadt",
                          "FMM": "Memmingen",
                          "DRS": "Dresden"}
inboundairlines = ["BT", "FH", "AZ", "DE", "4Y", "LG", "DLH", "SK", "U2", "SN", "H6", "RR", "VY", "FR", "UX", "SR", "LAV", "HN", "E2", "LX", "FHM", "XR", "HST", "CL", "EJU", "QS", "EZS", "LAS", "FB", "6Y", "GM", "KL", "CD", "TB", "OK", "EWG", "X8", "WK", "HV", "AF", "AP", "I2", "IB", "X3", "ART", "EW", "2L", "V7", "A5", "X1", "BUC", "BUU", "LH", "OS"]

outbounddepartureairports = {"HAJ": "Hannover",
                          "FRA": "Frankfurt",
                          "ZRH": "Zürich",
                          "LEJ": "Leipzig/Halle",
                          "NUE": "Nürnberg",
                          "SXB": "Straßburg",
                          "BSL": "Basel Mulhouse Freiburg",
                          "DUS": "Düsseldorf",
                          "EIN": "Eindhoven",
                          "BRU": "Brussels",
                          "LUX": "Luxemburg",
                          "FKB": "Karlsruhe / Baden-Baden",
                          "VIE": "Wien",
                          "HAM": "Hamburg",
                          "NRN": "Weeze",
                          "SCN": "Saarbrücken",
                          "KRK": "Rijeka",
                          "STR": "Stuttgart",
                          "CGN": "Köln Bonn",
                          "DTM": "Dortmund",
                          "FMO": "Münster/Osnabrück",
                          "GRQ": "Groningen",
                          "BRE": "Bremen",
                          "GWT": "Sylt",
                          "WAW": "Warschau",
                          "BRS": "Bristol",
                          "PRG": "Prag",
                          "MUC": "München",
                          "BER": "Berlin",
                          "BRN": "Bern",
                          "GRZ": "Graz",
                          "KLU": "Klagenfurt am Wörthersee",
                          "GVA": "Genf",
                          "SZG": "Salzburg",
                          "FDH": "Bodensee-Airport Friedrichshafen",
                          "BLL": "Billund",
                          "KSF": "Kassel",
                          "PAD": "Paderborn-Lippstadt",
                          "FMM": "Memmingen",
                          "DRS": "Dresden"}
outboundarrivalairports = {"PMI": "Palma de Mallorca"}
outboundairlines = ["BT", "FH", "AZ", "DE", "4Y", "LG", "DLH", "SK", "U2", "SN", "H6", "RR", "VY", "FR", "UX", "SR", "LAV", "HN", "E2", "LX", "FHM", "XR", "HST", "CL", "EJU", "QS", "EZS", "LAS", "FB", "6Y", "GM", "KL", "CD", "TB", "OK", "EWG", "X8", "WK", "HV", "AF", "AP", "I2", "IB", "X3", "ART", "EW", "2L", "V7", "A5", "X1", "BUC", "BUU", "LH", "OS"]


